# Generated by Django 4.1.7 on 2023-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pageCount', models.IntegerField(default=0)),
                ('thumbnailUrl', models.CharField(max_length=256, null=True)),
                ('shortDescription', models.CharField(max_length=256, null=True)),
                ('longDescription', models.TextField(null=True)),
            ],
        ),
    ]
