# Generated by Django 4.2.6 on 2023-10-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnailUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='images/review'),
        ),
    ]
